part of '../ble.dart';

/// [BleDevice] is the representation of a BLE device.
@freezed
abstract class BleDevice with _$BleDevice {
  const BleDevice._();

  /// [BleDevice] is the representation of a BLE device.
  const factory BleDevice({
    /// [macAddress] is the MAC address of the BLE device.
    /// Be careful, on Apple ecosystem, the MAC address is not the real identifier, is a generated by the platform
    /// and is hidden from the developer.
    required String macAddress,

    /// [name] is the name of the BLE device.
    /// Can be null if the device does not have a name or is not broadcasted.
    String? name,

    /// [rssi] is the signal strength of the BLE device.
    /// Can be null if the device does not have a signal strength due to a platform limitation.
    int? rssi,

    /// [txPower] is the transmission power of the BLE device.
    /// Can be null if the device does not have a transmission power due to a platform limitation.
    int? txPower,

    /// [manufacturerData] is the manufacturer data of the BLE device.
    @Default([]) List<BleManufacturerData> manufacturerData,

    /// [serviceData] is the service data of the BLE device.
    @Default([]) List<BleServiceData> serviceData,
  }) = _BleDevice;

  /// [fromJson] creates a [BleDevice] from a JSON map.
  factory BleDevice.fromJson(Map<String, dynamic> json) => _$BleDeviceFromJson(json);

  /// [serviceDataMap] returns the service data of the BLE device as a map of UUID to raw data.
  Map<int, List<int>> get serviceDataMap {
    final map = Map<int, List<int>>.from({});
    for (final serviceData in serviceData) {
      map[serviceData.uuid] = serviceData.data ?? <int>[];
    }

    return map;
  }

  /// [manufacturerDataMap] returns the manufacturer data of the BLE device as a map of company ID to raw data.
  Map<int, List<int>> get manufacturerDataMap {
    final map = Map<int, List<int>>.from({});
    for (final manufacturerData in manufacturerData) {
      map[manufacturerData.companyId] = manufacturerData.data ?? <int>[];
    }

    return map;
  }
}

/// [BleManufacturerData] is the representation of the manufacturer data of a BLE device.
@freezed
abstract class BleManufacturerData with _$BleManufacturerData {
  const BleManufacturerData._();

  /// [BleManufacturerData] is the representation of the manufacturer data of a BLE device.
  const factory BleManufacturerData({
    /// [companyId] is the company identifier of the manufacturer.
    @Default(0x0000) int companyId,

    /// [data] is the raw data of the manufacturer.
    List<int>? data,
  }) = _BleManufacturerData;

  /// [fromJson] creates a [BleManufacturerData] from a JSON map.
  factory BleManufacturerData.fromJson(Map<String, dynamic> json) => _$BleManufacturerDataFromJson(json);
}

/// [BleServiceData] is the representation of the service data of a BLE device.
@freezed
abstract class BleServiceData with _$BleServiceData {
  const BleServiceData._();

  /// [BleServiceData] is the representation of a BLE service.
  const factory BleServiceData({
    /// [uuid] is the UUID of the BLE service.
    required int uuid,

    /// [characteristics] is the list of characteristics of the BLE service.
    List<int>? data,
  }) = _BleServiceData;

  /// [fromJson] creates a [BleServiceData] from a JSON map.
  factory BleServiceData.fromJson(Map<String, dynamic> json) => _$BleServiceDataFromJson(json);
}
