name: layrz_sdk
description: "A Flutter SDK for Layrz, providing tools and utilities for integrating Layrz services into your Flutter applications."
version: 4.4.4
homepage: https://github.com/goldenm-software/layrz-sdk
repository: https://github.com/goldenm-software/layrz-sdk/tree/main/dart

topics:
  - layrz
  - sdk
  - models
  - iot
  - telemetry

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  collection: ^1.19.1
  dio: ^5.11.0
  flutter: { sdk: flutter }
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  layrz_i18n: ^1.0.0
  flutter_material_design_icons: ^3.1.0+7447
  layrz_logging: ^1.5.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  analyzer: ^10.2.0
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test: { sdk: flutter }
  freezed: ^3.2.5
  json_serializable: ^6.11.0
  test: ^1.26.2

flutter:
