part of '../mfa.dart';

/// Enumeration of supported multi-factor authentication (MFA) methods.
///
/// [MfaMethod] represents the different authentication algorithms that users
/// can register with their account for enhanced security. Each value is
/// serialized to JSON as an uppercase string (e.g., `TOTP`, `PASSKEY`).
/// Convert between enum and JSON using [toJson] and [fromJson].
@JsonEnum(alwaysCreate: true)
enum MfaMethod {
  /// Time-based One-Time Password (TOTP) algorithm.
  /// Typically generated by authenticator apps (Google Authenticator, Authy).
  /// JSON wire value: `TOTP`
  @JsonValue('TOTP')
  totp,

  /// HMAC-based One-Time Password (HOTP) algorithm.
  /// Similar to TOTP but counter-based instead of time-based.
  /// JSON wire value: `HOTP`
  @JsonValue('HOTP')
  hotp,

  /// WebAuthn/FIDO2 passkey credential.
  /// Represents a cryptographic credential (hardware key or platform
  /// authenticator) for passwordless authentication.
  /// JSON wire value: `PASSKEY`
  @JsonValue('PASSKEY')
  passkey,

  /// Backup code for account recovery.
  /// Single-use codes generated during MFA setup for emergency access.
  /// JSON wire value: `BACKUP_CODE`
  @JsonValue('BACKUP_CODE')
  backupCode;

  /// Returns the JSON representation of this MFA method (e.g., `TOTP`,
  /// `PASSKEY`).
  @override
  String toString() => toJson();

  /// Converts this [MfaMethod] to its JSON string representation.
  /// Returns `TOTP` as a default if the enum value is not recognized.
  String toJson() => _$MfaMethodEnumMap[this] ?? 'TOTP';

  /// Converts a JSON string representation to an [MfaMethod].
  /// Returns [MfaMethod.totp] as a default if the JSON value is not recognized.
  static MfaMethod fromJson(String json) {
    final found = _$MfaMethodEnumMap.entries.firstWhereOrNull((e) => e.value == json);
    return found?.key ?? MfaMethod.totp;
  }
}
