part of '../app.dart';

/// [_registeredAppListDecoder] decodes a raw listing `result` payload into a list of [RegisteredApp].
/// Used by listing queries (fetchAll, fetch, fetchPickAndApp, fillAuthorizations).
List<RegisteredApp> _registeredAppListDecoder(Object? json) {
  return List<RegisteredApp>.from(
    (json as List).map((e) {
      return RegisteredApp.fromJson(e as Map<String, dynamic>);
    }),
  );
}

/// [_registeredAppDecoder] decodes a single-object `result` payload into a [RegisteredApp].
/// Used by result-bearing mutations (register/edit-style).
RegisteredApp _registeredAppDecoder(Object? json) {
  return RegisteredApp.fromJson(json as Map<String, dynamic>);
}

/// An application registered in the Layrz platform.
///
/// [RegisteredApp] represents an app registered by a workspace or a partner,
/// including its identity, technology stack, legal and design information,
/// deployed [instances], imported entities, allowed reports, authorized map
/// layers, and push notification credentials.
@freezed
abstract class RegisteredApp with _$RegisteredApp {
  /// Private constructor used by the code generator.
  const RegisteredApp._();

  /// Constructs an immutable [RegisteredApp].
  const factory RegisteredApp({
    /// The unique identifier of the app.
    required String id,

    /// The name of the app. It is a fixed name, not a translation key.
    required String name,

    /// The technology of the app.
    @JsonKey(unknownEnumValue: AppTechnology.flutter) @Default(AppTechnology.flutter) AppTechnology technology,

    /// The legal information of the app.
    AppLegal? legalInformation,

    /// The design information of the app.
    AppDesign? designInformation,

    /// The user-facing nickname of the app.
    required String nickname,

    /// Whether the app has been customized, or null when not applicable.
    bool? isCustomized,

    /// The list of deployed instances of the app, or null when not
    /// requested.
    List<AppInstance>? instances,

    /// The list of assets imported into the app, or null when not
    /// requested.
    List<Asset>? importedAssets,

    /// The list of devices imported into the app, or null when not
    /// requested.
    List<Device>? importedDevices,

    /// The list of users imported into the app, or null when not
    /// requested.
    List<User>? importedUsers,

    /// The list of users granted access to the app, or null when not
    /// requested.
    List<User>? keychain,

    /// The identifier of the source this app was created from.
    required String sourceId,

    /// The owner of the app.
    ///
    /// Important: this field is only available when the query is made from
    /// `/goldenm/graphql`.
    User? owner,

    /// The list of reports allowed to be generated by the app, or null when
    /// not requested.
    List<CustomReport>? allowedReports,

    /// The identifier of the fixed workspace of the app, or null when not
    /// applicable.
    String? fixedWorkspaceId,

    /// The fixed workspace of the app, or null when not applicable.
    Workspace? fixedWorkspace,

    /// The list of map layers authorized to be used by the app.
    @Default([]) List<MapLayer> authorizedLayers,

    /// The decrypted iOS Firebase credentials for `layrz_push`, or null when
    /// not set or not requested.
    PushSecrets? iosPushSecrets,

    /// The decrypted Android Firebase credentials for `layrz_push`, or null
    /// when not set or not requested.
    PushSecrets? androidPushSecrets,

    /// Whether the backend holds service-account push credentials; content
    /// is never exposed. Null when not requested.
    bool? hasSvcPushSecrets,
  }) = _RegisteredApp;

  /// Deserializes a [RegisteredApp] from a JSON map.
  factory RegisteredApp.fromJson(Map<String, dynamic> json) => _$RegisteredAppFromJson(json);

  // coverage:ignore-start
  /// Fetches all registered apps from the server.
  ///
  /// Returns a list of [RegisteredApp] with the required contextual
  /// information. Authentication is carried solely via the connector's
  /// `Authorization` header, built from [apiToken].
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns an empty list on any error (network failure, authentication
  /// failure, or server error). Errors are logged internally.
  static Future<List<RegisteredApp>> fetchAll({
    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.query(
        GqlQuery(variables: [])..add(
          GqlField(name: 'registeredApps', args: {})
            ..add(GqlField(name: 'status'))
            ..add(
              GqlField(name: 'result')
                ..add(GqlField(name: 'id'))
                ..add(GqlField(name: 'name'))
                ..add(GqlField(name: 'nickname'))
                ..add(GqlField(name: 'sourceId'))
                ..add(GqlField(name: 'designInformation', fragment: AppDesign.reducedFragment))
                ..add(
                  GqlField(name: 'instances')
                    ..add(GqlField(name: 'id'))
                    ..add(GqlField(name: 'appId'))
                    ..add(GqlField(name: 'platform'))
                    ..add(GqlField(name: 'host'))
                    ..add(GqlField(name: 'status')),
                ),
            ),
        ),
        _registeredAppListDecoder,
      );

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return [];
      }

      return response.result ?? [];
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/fetchAll(): General exception => $e\n$stack");
      return [];
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// Fetches a single registered app by its [id] from the server.
  ///
  /// Returns a [RegisteredApp] with the required contextual information, or
  /// null on error. Authentication is carried solely via the connector's
  /// `Authorization` header, built from [apiToken].
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  static Future<RegisteredApp?> fetch({
    /// The identifier of the [RegisteredApp] to fetch.
    required String id,

    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.query(
        GqlQuery(
          variables: [
            GqlVariable(name: 'id', type: .id, isRequired: true, value: id),
          ],
        )..add(
          GqlField(name: 'registeredApps', args: {'id': 'id'})
            ..add(GqlField(name: 'status'))
            ..add(GqlField(name: 'result', fragment: fragment)),
        ),
        _registeredAppListDecoder,
      );

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return null;
      }

      return response.result?.first;
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/fetch(): General exception => $e\n$stack");
      return null;
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// Sets push notification secrets for the app.
  ///
  /// Accepts optional Firebase secrets for iOS, Android, and a service
  /// account; only the provided (non-null) secrets are sent to the server.
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns true on success, false on error.
  static Future<bool> setPushSecrets({
    /// The identifier of the app to set push secrets for.
    required String appId,

    /// The raw iOS Firebase credentials JSON, or null to leave unchanged.
    String? iosPushSecrets,

    /// The raw Android Firebase credentials JSON, or null to leave
    /// unchanged.
    String? androidPushSecrets,

    /// The raw service-account Firebase credentials JSON, or null to leave
    /// unchanged.
    String? svcPushSecrets,

    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final variables = <GqlVariable>[
        GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
      ];

      if (iosPushSecrets != null) {
        variables.add(GqlVariable(name: 'iosPushSecrets', type: .string, isRequired: false, value: iosPushSecrets));
      }
      if (androidPushSecrets != null) {
        variables.add(
          GqlVariable(name: 'androidPushSecrets', type: .string, isRequired: false, value: androidPushSecrets),
        );
      }
      if (svcPushSecrets != null) {
        variables.add(GqlVariable(name: 'svcPushSecrets', type: .string, isRequired: false, value: svcPushSecrets));
      }

      final response = await connector.mutate(
        GqlMutation(
          variables: variables,
          name: 'setPushSecrets',
        )..add(
          GqlField(
            name: 'setPushSecrets',
            args: {
              'appId': 'appId',
              if (iosPushSecrets != null) 'iosPushSecrets': 'iosPushSecrets',
              if (androidPushSecrets != null) 'androidPushSecrets': 'androidPushSecrets',
              if (svcPushSecrets != null) 'svcPushSecrets': 'svcPushSecrets',
            },
          )..add(GqlField(name: 'status')),
        ),
      );

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/setPushSecrets(): General exception => $e\n$stack");
      return false;
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// Grants a user access to the app.
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns true on success, false on error.
  static Future<bool> grantAccessToApp({
    /// The identifier of the user to grant access to.
    required String userId,

    /// The identifier of the app to grant access to.
    required String appId,

    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.mutate(
        GqlMutation(
          variables: [
            GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
            GqlVariable(name: 'userId', type: .id, isRequired: true, value: userId),
          ],
          name: 'grantAccessToApp',
        )..add(
          GqlField(name: 'grantAccessToApp', args: {'appId': 'appId', 'userId': 'userId'})
            ..add(GqlField(name: 'status')),
        ),
      );

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/grantAccessToApp(): General exception => $e\n$stack");
      return false;
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// Grants multiple users access to the app.
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns true on success, false on error.
  static Future<bool> grantMultipleAccessToApp({
    /// The identifiers of the users to grant access to.
    required List<String> usersIds,

    /// The identifier of the app to grant access to.
    required String appId,

    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.mutate(
        GqlMutation(
          variables: [
            GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
            GqlVariable(
              name: 'userIds',
              type: .list(of: .id, isRequired: true),
              isRequired: true,
              value: usersIds,
            ),
          ],
          name: 'grantMultipleAccessToApp',
        )..add(
          GqlField(
            name: 'grantMultipleAccessToApp',
            args: {'appId': 'appId', 'userIds': 'userIds'},
          )..add(GqlField(name: 'status')),
        ),
      );

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/grantMultipleAccessToApp(): General exception => $e\n$stack");
      return false;
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// Revokes a user's access to the app.
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns true on success, false on error.
  static Future<bool> revokeAccessToApp({
    /// The identifier of the user to revoke access from.
    required String userId,

    /// The identifier of the app to revoke access from.
    required String appId,

    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.mutate(
        GqlMutation(
          variables: [
            GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
            GqlVariable(name: 'userId', type: .id, isRequired: true, value: userId),
          ],
          name: 'revokeAccessToApp',
        )..add(
          GqlField(name: 'revokeAccessToApp', args: {'appId': 'appId', 'userId': 'userId'})
            ..add(GqlField(name: 'status')),
        ),
      );

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/revokeAccessToApp(): General exception => $e\n$stack");
      return false;
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// Imports assets into the app.
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns true on success, false on error.
  static Future<bool> importAssetsIntoApp({
    /// The identifiers of the assets to import.
    required List<String> assetsIds,

    /// The identifier of the app to import assets into.
    required String appId,

    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.mutate(
        GqlMutation(
          variables: [
            GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
            GqlVariable(
              name: 'assetsIds',
              type: .list(of: .id, isRequired: true),
              isRequired: true,
              value: assetsIds,
            ),
          ],
          name: 'importAssetsIntoApp',
        )..add(
          GqlField(
            name: 'importAssetsIntoApp',
            args: {'appId': 'appId', 'assetsIds': 'assetsIds'},
          )..add(GqlField(name: 'status')),
        ),
      );

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/importAssetsIntoApp(): General exception => $e\n$stack");
      return false;
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// Revokes assets from the app.
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns true on success, false on error.
  static Future<bool> revokeAssetsFromApp({
    /// The identifiers of the assets to revoke.
    required List<String> assetsIds,

    /// The identifier of the app to revoke assets from.
    required String appId,

    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.mutate(
        GqlMutation(
          variables: [
            GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
            GqlVariable(
              name: 'assetsIds',
              type: .list(of: .id, isRequired: true),
              isRequired: true,
              value: assetsIds,
            ),
          ],
          name: 'revokeAssetsFromApp',
        )..add(
          GqlField(
            name: 'revokeAssetsFromApp',
            args: {'appId': 'appId', 'assetsIds': 'assetsIds'},
          )..add(GqlField(name: 'status')),
        ),
      );

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/revokeAssetsFromApp(): General exception => $e\n$stack");
      return false;
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// Imports devices into the app.
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns true on success, false on error.
  static Future<bool> importDevicesIntoApp({
    /// The identifiers of the devices to import.
    required List<String> devicesIds,

    /// The identifier of the app to import devices into.
    required String appId,

    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.mutate(
        GqlMutation(
          variables: [
            GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
            GqlVariable(
              name: 'devicesIds',
              type: .list(of: .id, isRequired: true),
              isRequired: true,
              value: devicesIds,
            ),
          ],
          name: 'importDevicesIntoApp',
        )..add(
          GqlField(
            name: 'importDevicesIntoApp',
            args: {'appId': 'appId', 'devicesIds': 'devicesIds'},
          )..add(GqlField(name: 'status')),
        ),
      );

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/importDevicesIntoApp(): General exception => $e\n$stack");
      return false;
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// Revokes devices from the app.
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns true on success, false on error.
  static Future<bool> revokeDevicesFromApp({
    /// The identifiers of the devices to revoke.
    required List<String> devicesIds,

    /// The identifier of the app to revoke devices from.
    required String appId,

    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.mutate(
        GqlMutation(
          variables: [
            GqlVariable(name: 'appId', type: .id, isRequired: true, value: appId),
            GqlVariable(
              name: 'devicesIds',
              type: .list(of: .id, isRequired: true),
              isRequired: true,
              value: devicesIds,
            ),
          ],
          name: 'revokeDevicesFromApp',
        )..add(
          GqlField(
            name: 'revokeDevicesFromApp',
            args: {'appId': 'appId', 'devicesIds': 'devicesIds'},
          )..add(GqlField(name: 'status')),
        ),
      );

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/revokeDevicesFromApp(): General exception => $e\n$stack");
      return false;
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// Registers a new app without customization on the server.
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns a [StandardResponse] tuple of `(ApiStatus, errors,
  /// RegisteredApp?)`: on an internal error,
  /// `(ApiStatus.internalError, null, null)`; on any other non-ok status,
  /// `(status, errors, null)`; on success, `(status, errors, createdApp)`.
  static Future<StandardResponse<RegisteredApp>> registerWithoutCustomization({
    /// The raw `AppWithoutCustomizationInput` payload.
    required Map<String, dynamic> data,

    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.mutate(
        GqlMutation(
          variables: [
            GqlVariable(
              name: 'data',
              type: GqlVariableType.input(of: 'AppWithoutCustomizationInput'),
              isRequired: true,
              value: data,
            ),
          ],
          name: 'registerAppWithoutCustomization',
        )..add(
          GqlField(name: 'registerAppWithoutCustomization', args: {'data': 'data'})
            ..add(GqlField(name: 'status'))
            ..add(GqlField(name: 'result', fragment: fragment)),
        ),
        _registeredAppDecoder,
      );

      if (response.status == .internalError) {
        onResponse?.call(response.status.toJson());
        return (ApiStatus.internalError, null, null);
      }

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return (response.status, response.errors, null);
      }

      return (response.status, response.errors, response.result);
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/registerWithoutCustomization(): General exception => $e\n$stack");
      return (ApiStatus.internalError, null, null);
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// Registers a new app with customization on the server.
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns a [StandardResponse] tuple of `(ApiStatus, errors,
  /// RegisteredApp?)`: on an internal error,
  /// `(ApiStatus.internalError, null, null)`; on any other non-ok status,
  /// `(status, errors, null)`; on success, `(status, errors, createdApp)`.
  static Future<StandardResponse<RegisteredApp>> registerWithCustomization({
    /// The raw `AppInput` payload.
    required Map<String, dynamic> data,

    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.mutate(
        GqlMutation(
          variables: [
            GqlVariable(
              name: 'data',
              type: GqlVariableType.input(of: 'AppInput'),
              isRequired: true,
              value: data,
            ),
          ],
          name: 'registerAppWithCustomization',
        )..add(
          GqlField(name: 'registerAppWithCustomization', args: {'data': 'data'})
            ..add(GqlField(name: 'status'))
            ..add(GqlField(name: 'result', fragment: fragment)),
        ),
        _registeredAppDecoder,
      );

      if (response.status == .internalError) {
        onResponse?.call(response.status.toJson());
        return (ApiStatus.internalError, null, null);
      }

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return (response.status, response.errors, null);
      }

      return (response.status, response.errors, response.result);
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/registerWithCustomization(): General exception => $e\n$stack");
      return (ApiStatus.internalError, null, null);
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// Edits an existing app on the server.
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns a [StandardResponse] tuple of `(ApiStatus, errors,
  /// RegisteredApp?)`: on an internal error,
  /// `(ApiStatus.internalError, null, null)`; on any other non-ok status,
  /// `(status, errors, null)`; on success, `(status, errors, updatedApp)`.
  static Future<StandardResponse<RegisteredApp>> edit({
    /// The identifier of the app to edit.
    required String id,

    /// The raw `AppInput` payload.
    required Map<String, dynamic> data,

    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.mutate(
        GqlMutation(
          variables: [
            GqlVariable(
              name: 'data',
              type: GqlVariableType.input(of: 'AppInput'),
              isRequired: true,
              value: data,
            ),
          ],
          name: 'editApp',
        )..add(
          GqlField(name: 'editApp', args: {'data': 'data'})
            ..add(GqlField(name: 'status'))
            ..add(GqlField(name: 'result', fragment: fragment)),
        ),
        _registeredAppDecoder,
      );

      if (response.status == .internalError) {
        onResponse?.call(response.status.toJson());
        return (ApiStatus.internalError, null, null);
      }

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return (response.status, response.errors, null);
      }

      return (response.status, response.errors, response.result);
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/edit(): General exception => $e\n$stack");
      return (ApiStatus.internalError, null, null);
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// Deletes an app from the server by [id].
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns true on success, false on error.
  static Future<bool> delete({
    /// The identifier of the app to delete.
    required String id,

    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.mutate(
        GqlMutation(
          variables: [
            GqlVariable(name: 'id', type: .id, isRequired: true, value: id),
          ],
          name: 'deleteApp',
        )..add(
          GqlField(name: 'deleteApp', args: {'id': 'id'})..add(GqlField(name: 'status')),
        ),
      );

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return false;
      }
      return true;
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/delete(): General exception => $e\n$stack");
      return false;
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// Loads a registered app from the server by [appId], for a given
  /// [platform] and [technology].
  ///
  /// This mutation is not authenticated with an `apiToken` since it is used
  /// during app bootstrap, before a user session exists.
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns the loaded [RegisteredApp] on success, null on error.
  static Future<RegisteredApp?> load({
    /// The identifier of the app to load.
    required String appId,

    /// The platform the app is being loaded for.
    required AppPlatform platform,

    /// The technology the app is being loaded for.
    required AppTechnology technology,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri);
    try {
      final response = await connector.mutate(
        GqlMutation(
          variables: [
            GqlVariable(name: 'appId', type: .string, isRequired: true, value: appId),
            GqlVariable(
              name: 'platform',
              type: .enum_(of: 'AppPlatform'),
              isRequired: true,
              value: platform.toJson(),
            ),
            GqlVariable(
              name: 'technology',
              type: .enum_(of: 'AppTechnology'),
              isRequired: true,
              value: technology.toJson(),
            ),
          ],
        )..add(
          GqlField(name: 'loadApp', args: {'platform': 'platform', 'technology': 'technology', 'appId': 'appId'})
            ..add(GqlField(name: 'status'))
            ..add(
              GqlField(name: 'result')
                ..add(GqlField(name: 'id'))
                ..add(GqlField(name: 'name'))
                ..add(GqlField(name: 'nickname'))
                ..add(GqlField(name: 'technology'))
                ..add(GqlField(name: 'sourceId'))
                ..add(GqlField(name: 'legalInformation', fragment: AppLegal.fragment))
                ..add(GqlField(name: 'designInformation', fragment: AppDesign.fragment)),
            ),
        ),
        (json) => json != null ? RegisteredApp.fromJson(Map<String, dynamic>.from(json as Map)) : null,
      );

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return null;
      }

      return response.result;
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/load(): General exception => $e\n$stack");
      return null;
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// The GraphQL fragment for a [RegisteredApp].
  static GqlFragment get fragment => GqlFragment(name: 'registeredAppFragment', onType: 'RegisteredApp')
    ..add(GqlField(name: 'id'))
    ..add(GqlField(name: 'name'))
    ..add(GqlField(name: 'nickname'))
    ..add(GqlField(name: 'isCustomized'))
    ..add(GqlField(name: 'technology'))
    ..add(GqlField(name: 'sourceId'))
    ..add(GqlField(name: 'instances', fragment: AppInstance.fragment))
    ..add(GqlField(name: 'designInformation', fragment: AppDesign.fragment))
    ..add(GqlField(name: 'legalInformation', fragment: AppLegal.fragment))
    ..add(GqlField(name: 'iosPushSecrets', fragment: PushSecrets.fragment))
    ..add(GqlField(name: 'androidPushSecrets', fragment: PushSecrets.fragment))
    ..add(GqlField(name: 'mapLayers', fragment: MapLayer.fragment))
    ..add(
      GqlField(
        name: 'allowedReports',
        fields: [
          GqlField(name: 'id'),
          GqlField(name: 'code'),
        ],
      ),
    )
    ..add(GqlField(name: 'hasSvcPushSecrets'));
  // coverage:ignore-end

  // coverage:ignore-start
  /// Fetches the registered apps for the pick-an-app view.
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns a list of [RegisteredApp] on success, an empty list on error.
  static Future<List<RegisteredApp>?> fetchPickAndApp({
    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// The internal identifier of the app to filter by.
    required AppInternalIdentifier appIdentifier,

    /// The identifier of a specific app to filter by, or null to fetch all
    /// apps matching [appIdentifier].
    String? id,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.query(
        GqlQuery(
          variables: [
            GqlVariable(
              name: 'appIdentifier',
              type: .enum_(of: 'InternalIdentifier'),
              isRequired: true,
              value: appIdentifier.toJson(),
            ),
            if (id != null) GqlVariable(name: 'id', type: .id, value: id),
          ],
        )..add(
          GqlField(
              name: 'registeredApps',
              args: {
                'appIdentifier': 'appIdentifier',
                if (id != null) 'id': 'id',
              },
            )
            ..add(GqlField(name: 'status'))
            ..add(GqlField(name: 'result', fragment: fragment)),
        ),
        _registeredAppListDecoder,
      );

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return [];
      }

      return response.result ?? [];
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/fetchAll(): General exception => $e\n$stack");
      return [];
    }
  }
  // coverage:ignore-end

  // coverage:ignore-start
  /// Fetches this app's authorization-related fields (imported assets,
  /// imported devices, and keychain) from the server.
  ///
  /// Optional callback invoked with the raw status code string of the
  /// response. Called once per invocation, regardless of success or
  /// failure.
  ///
  /// Returns a [RegisteredApp] populated with the authorization fields on
  /// success, null on error.
  Future<RegisteredApp?> fillAuthorizations({
    /// The API token for authentication. Obtain via the `login` mutation
    /// on the GraphQL API.
    required String apiToken,

    /// The Layrz GraphQL API endpoint (e.g.,
    /// `https://api.example.com/graphql`).
    required Uri uri,

    /// Optional callback invoked with the raw status code string of the
    /// response.
    void Function(String statusCode)? onResponse,
  }) async {
    final connector = LayrzConnector(uri: uri, apiToken: apiToken);
    try {
      final response = await connector.query(
        GqlQuery(
          variables: [
            GqlVariable(name: 'id', type: .id, isRequired: true, value: id),
          ],
        )..add(
          GqlField(name: 'registeredApps', args: {'id': 'id'})
            ..add(GqlField(name: 'status'))
            ..add(
              GqlField(
                name: 'result',
                fields: [
                  GqlField(name: 'id'),
                  GqlField(name: 'name'),
                  GqlField(name: 'nickname'),
                  GqlField(name: 'isCustomized'),
                  GqlField(name: 'technology'),
                  GqlField(name: 'sourceId'),
                  GqlField(
                    name: 'importedAssets',
                    fields: [
                      GqlField(name: 'id'),
                      GqlField(name: 'name'),
                      GqlField(name: 'dynamicIcon', fragment: Avatar.fragment),
                    ],
                  ),
                  GqlField(
                    name: 'importedDevices',
                    fields: [
                      GqlField(name: 'id'),
                      GqlField(name: 'name'),
                      GqlField(name: 'ident'),
                    ],
                  ),
                  GqlField(
                    name: 'keychain',
                    fields: [
                      GqlField(name: 'id'),
                      GqlField(name: 'name'),
                      GqlField(name: 'dynamicAvatar', fragment: Avatar.fragment),
                    ],
                  ),
                ],
              ),
            ),
        ),
        _registeredAppListDecoder,
      );

      if (response.status != .ok) {
        onResponse?.call(response.status.toJson());
        return null;
      }

      return response.result?.first;
    } catch (e, stack) {
      Log.critical("layrz_sdk/RegisteredApp/fillAuthorizations(): General exception => $e\n$stack");
      return null;
    }
  }
  // coverage:ignore-end
}

/// A custom report definition allowed to be generated by one or more apps.
///
/// [CustomReport] pairs a report [code] with the list of [RegisteredApp]s
/// authorized to generate it. It forms a circular reference with
/// [RegisteredApp] (via [RegisteredApp.allowedReports]) and therefore lives
/// in the same library as [RegisteredApp].
@freezed
abstract class CustomReport with _$CustomReport {
  /// Private constructor used by the code generator.
  const CustomReport._();

  /// Constructs an immutable [CustomReport].
  const factory CustomReport({
    /// The unique identifier of the report.
    required String id,

    /// The code of the report.
    required String code,

    /// The list of apps allowed to generate this report, or null when not
    /// requested.
    List<RegisteredApp>? allowedApps,
  }) = _CustomReport;

  /// Deserializes a [CustomReport] from a JSON map.
  factory CustomReport.fromJson(Map<String, dynamic> json) => _$CustomReportFromJson(json);
}
